spring.application.name=hms

#database configuration
spring.datasource.driverClassName : com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/HMS
spring.datasource.username = root
spring.datasource.password = MySql@1107
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

# Run data.sql AFTER Hibernate has created the tables
spring.jpa.defer-datasource-initialization=true
# Needed for MySQL, otherwise data.sql is skipped
spring.sql.init.mode=always