ALTER TABLE user_login AUTO_INCREMENT = 1001;
ALTER TABLE doctors AUTO_INCREMENT = 2001;
ALTER TABLE appointments AUTO_INCREMENT = 5001;
ALTER TABLE prescriptions AUTO_INCREMENT = 6001;
ALTER TABLE prescription_items AUTO_INCREMENT = 7001;
ALTER TABLE medicines AUTO_INCREMENT = 8001;
ALTER TABLE bills AUTO_INCREMENT = 9001;
ALTER TABLE patients AUTO_INCREMENT = 10001;